
server:
  enabled: true
  address: ":9091"
  timeout: 1m
  pprof: true

logger:
  level: "info"

controller:
  layer4Metrics:
    enabled: true
    requiredLabels:
#      - "source.host"
#      - "source.port"
#      - "destination.host"
#      - "destination.port"

sniffer.ifaces: 'any'
sniffer.engine: pcap # or xdp
sniffer.ipv4Only: true
sniffer.file: "/tmp/apm-worker.pcap"

sniffer.protocols:
  rules:
#    - name: "redis"
#      protocol: "redis"
#      port: 6379

    - name: "http-example"
      protocol: "http"
      port: 9200
##
#    - name: "mysql"
#      protocol: "mysql"
#      port: 3306

#    - name: "grpc"
#      protocol: "grpc"
#      port: 8085
#
#    - name: dns
#      protocol: "dns"
#      port: 53

#    - name: mongodb
#      protocol: "mongodb"
#      port: 27017

#    - name: "postgresql"
#      protocol: "postgresql"
#      port: 5432

    - name: "kafka"
      protocol: "kafka"
      port: 9092

    - name: amqp
      protocol: "amqp"
      port: 5672

processor:
  - name: roundtripstometrics
    config:
      http:
        requireLabels:
          - "server.host"
          - "server.port"
          - "request.method"
          - "request.path"
          - "response.status_code"

      kafka:
        requireLabels:
          - request.api

      amqp:
        requireLabels:
          - "request.class"
          - "request.method"

  - name: roundtripstotraces
    config:

#  - name: roundtripsfilter
#    config:

pipeline:
  - name: "traces/common"
    processors:
      - roundtripstotraces

  - name: "metrics/common"
    processors:
      - roundtripstometrics

metricsStorage:
  enabled: true
  expired: 5m
  vmHistogram: true

exporter:
  traces:
    enabled: false
    endpoint: http://localhost:4318/v1/traces
    batch: 10
    interval: 3s

  metrics:
    enabled: false
    endpoint: http://localhost:4318/prometheus/write
    interval: 1m

  roundtrips:
    enabled: true
    console: false
    filename: "roundtrips.log"
    maxSize: 100
    maxBackups: 10
    maxAge: 30
