
server:
  enabled: true
  address: ":9091"
  timeout: 1m
  pprof: true

logger:
  level: "debug"
  stdout: true

controller:
  layer4Metrics:
    enabled: true
    requiredLabels:
#      - "source.host"
#      - "source.port"
#      - "destination.host"
#      - "destination.port"

sniffer.ifaces: 'any'
sniffer.engine: pcap
sniffer.ipVersion: ''
sniffer.blockNum: 128
#sniffer.file: "/tmp/apm-worker.pcap"

decoder.protocols:
  mongodb:
    enableOkCode: false

sniffer.protocols:
  rules:
#    - name: "redis"
#      protocol: "redis"
#      ports: [6379]
#
    - name: "http"
      protocol: "http"
      ports: [80]

#    - name: "mysql"
#      protocol: "mysql"
#      ports: [3306]
#
#    - name: "grpc"
#      protocol: "grpc"
#      ports: [8085]

#    - name: "http2"
#      protocol: "http2"
#      ports: [8085]

#    - name: dns
#      protocol: "dns"
#      ports: [53]

#    - name: mongodb
#      protocol: "mongodb"
#      ports: [27017]
#
#    - name: "postgresql"
#      protocol: "postgresql"
#      ports: [5432]
#
#    - name: "kafka"
#      protocol: "kafka"
#      ports: [9092]
#
    - name: amqp
      protocol: "amqp"
      ports: [5672]

processor:
  - name: roundtripstometrics
    config:
      http:
        requireLabels:
#          - "server.host"
#          - "server.port"
#          - "request.method"
#          - "request.path"
#          - "request.remote_host"
#          - "response.status_code"

      redis:
        requireLabels:

      kafka:
        requireLabels:
#          - request.api
#          - request.version

      amqp:
        requireLabels:
          - "request.class"
          - "request.method"

  - name: roundtripstotraces
    config:

#  - name: roundtripsfilter
#    config:

pipeline:
#  - name: "traces/common"
#    processors:
#      - roundtripstotraces
##
  - name: "metrics/common"
    processors:
      - roundtripstometrics

metricsStorage:
  enabled: true
  expired: 5m
  vmHistogram: false

exporter:
  traces:
    enabled: false
    endpoint: http://localhost:4318/v1/traces
    batch: 10
    interval: 3s

  metrics:
    enabled: false
    endpoint: http://localhost:8428/api/v1/write
    interval: 15s

  roundtrips:
    enabled: false
    console: true
    filename: "packetd.roundtrips"
    maxSize: 100
    maxBackups: 10
    maxAge: 30
